name: PHP Code Sniffer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  PHPCS:
    name: PHPCS Scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: php-actions/composer@v6
        with:
          command: install
          php_version: "8.1"
          args: "--ignore-platform-req=ext-zip"

      - name: Run PHP_CodeSniffer
        run: composer phpcs:check
