name: PHP Static Analyzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  PHPStan:
    name: PHPStan Scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: php-actions/composer@v6
        with:
          command: install
          php_version: "8.1"

      - name: Run PHPStan
        run: composer phpstan:check
